### ISSUE TITLE
spaces after apostrophe are too large

### ISSUE THREAD

**Issue by j10sanders** [wild-flame/jekyll-simple#4]
Words with an apostrophe get a large space after the apostrophe.  I don't know what setting is causing this spacing issue.

Syntax ends up looking like this:

won'  t
can'  t
don'  t
wasn'  t

**Comment by j10sanders** [comment]
appears it is an issue with Microsoft YaHei

http://answers.microsoft.com/en-us/msoffice/forum/msoffice_word-mso_winother/extra-font-added-after-apostrophe/78ba3986-d51f-45c7-beec-edf3b0715cdd

**Comment by j10sanders** [comment]
I removed Microsoft YaHei from the `_sass/_base.scss`  and the issue is resolved

**Comment by danielvmoore** [comment]
Thank you, j10sanders! This did the trick! :)

**Comment by wild-flame** [comment]
Thank u @j10sanders @danielvmoore . I would consider remove Microsoft YaHei, I used it as a fallback for those who don't have proper CJK fonts on their local machine.

Because Microsoft YaHei is one of the CJK fonts so if you're not using these language, just remove it :D
