### ISSUE TITLE
Unwanted space after apostrophe

### ISSUE THREAD

**Issue by acarril** [wild-flame/jekyll-simple#6]
After every apostrophe (e.g. the one in "You'll") the template adds a lot of unwanted space, so you see something like the following:
![jekyll_simple_issue](https://cloud.githubusercontent.com/assets/9773292/24931335/e01c2efc-1eda-11e7-9ea8-29861f2c4b52.png)
Do you have any idea of what could be producing this?

**Comment by wild-flame** [comment]
Same as https://github.com/wild-flame/jekyll-simple/issues/4
