### ISSUE TITLE
hi, can you add the next button to move into the next page?

### ISSUE THREAD

**Issue by meettyj** [wild-flame/jekyll-simple#7]
I have so many pages and they all stuck in one page, which make the page seems very long. I tried to figure it by myself but I failed. Can you help me?? Thx!

**Comment by wild-flame** [comment]
You mean pagination?

**Comment by meettyj** [comment]
yes! can you help me?

**Comment by wild-flame** [comment]
**You can refer to this document: https://jekyllrb.com/docs/pagination/.** 

It has a lot of the info you need to create pagination on your own.

Just fork this repo and create pagination on your own, I would help you when you are in trouble. When you finishing everything, create a pull request. Then I would add you as the contributor. 

**p.s this one would also be helpful:
https://help.shopify.com/themes/liquid/objects/paginate**

**Comment by meettyj** [comment]
hi, the pagination is settle down and a PR is on the way.
